language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database church_cells_test_db;' -U postgres
# command to run tests
script:
  - manage.py test